---
name: Lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint:
    runs_on: ubuntu-latest
    
    steps:
      - uses: "actions/checkout@v4"

      - uses: astral-sh/ruff-action@v2
      - run: ruff check .
      - run: ruff check --select I games
      - run: ruff format --check
